### ISSUE TITLE
I met some problems when running hdf5 datasets

### ISSUE THREAD

**Issue by lostgreen** [intellistream/CANDY#31]
When I ran the Evaluation scripts, the fvecs datasets SIFT was finished correctly, but when it came to hdf5 datasets like glove,sun and msong,the scripts threw error like this:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/zhang/CANDY/build/benchmark/results/scanL2E2E/flat/Msong/onlineInsert_result.csv'` how can i fix it?

**Comment by Rubatozh** [comment]
Could you provide any details on how you built the project? Or could you provide the program log before the Python error?

**Comment by ShuhaoZhangTony** [comment]
> When I ran the Evaluation scripts, the fvecs datasets SIFT was finished correctly, but when it came to hdf5 datasets like glove,sun and msong,the scripts threw error like this: `FileNotFoundError: [Errno 2] No such file or directory: '/home/zhang/CANDY/build/benchmark/results/scanL2E2E/flat/Msong/onlineInsert_result.csv'` how can i fix it?

Hi Guowen, from the error message, it is very likely that that file is not succesfully produced, can you please post more information on how you run the program?

**Comment by lostgreen** [comment]
I just download the dataset and put it into the right directory, i solved this problem by changing hdf5 into fvecs, details i've already forgot, i just followed the steps in README
